apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: apps
    repoURL: 'https://github.com/tlakusanisiwelane/my-argocd-project.git'
    targetRevision: HEAD
  project: default


