apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec::
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.0
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    namespace: cert-manager
    name: kind
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true